version: 1.0.{build}
image: Visual Studio 2017
nuget:
  disable_publish_on_pr: true
configuration: Release
install:
- cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe
before_build:
- cmd: nuget restore
build:
 include_nuget_references: true
  project: Arquitetura.sln
  parallel: true
  verbosity: minimal
 deploy:
- provider: NuGet
  api_key:
    secure: N3syhqs5cHi80QeyACpiJyZzqPf9EyWjm8zb6RYwn+6V3NSPUwhMvZyz04KseqGg